import { Book, Translations } from './types';

export const translations: Translations = {
  en: {
    appTitle: "Yeon.",
    heroTitle: "Embrace\nConnection",
    heroSubtitle: "Welcome to Yeon (연), where books find new paths. A mindful exchange community for Korean literature in Australia.",
    findBooks: "Discover Books",
    addBook: "Share a Story",
    searchPlaceholder: "Search for titles, authors, or meaning...",
    filterByState: "Region",
    allStates: "Everywhere",
    safetyTitle: "Mindful Exchange",
    safetyDesc: "Trust and safety are the foundation of our community.",
    safetyPoint1: "Meet in open, public spaces like libraries or cafes.",
    safetyPoint2: "Exchange during daylight to ensure clarity and safety.",
    safetyPoint3: "Connect with verified members through reviews.",
    points: "credits",
    condition: "Condition",
    location: "Origin",
    exchange: "Connect",
    footerDisclaimer: "Yeon is a platform for connection. We facilitate the meeting of minds but are not party to transactions.",
    legal: "Terms of Harmony",
    statsTitle: "Community Flow",
    login: "Sign In",
    welcome: "Welcome",
    newArrivals: "Discover Stories",
    howItWorks: "The Journey",
    step1Title: "Release",
    step1Desc: "Let go of books you've loved.",
    step2Title: "Discover",
    step2Desc: "Find new wisdom near you.",
    step3Title: "Connect",
    step3Desc: "Meet safely and share the joy.",
    damagePolicy: "Restoration Policy",
    damageDesc: "Guidelines for respect and care of shared books."
  },
  ko: {
    appTitle: "연 (Yeon).",
    heroTitle: "책, 그리고\n연(緣)을 잇다",
    heroSubtitle: "책이 머무는 곳에서 새로운 인연이 시작됩니다. 호주 한인들을 위한 깊이 있는 독서 교환 커뮤니티.",
    findBooks: "책 발견하기",
    addBook: "이야기 나누기",
    searchPlaceholder: "제목, 작가, 혹은 마음을 검색하세요...",
    filterByState: "지역",
    allStates: "전체",
    safetyTitle: "안전한 만남",
    safetyDesc: "신뢰는 우리 커뮤니티의 가장 중요한 가치입니다.",
    safetyPoint1: "도서관이나 카페 같은 열린 공간에서 만나세요.",
    safetyPoint2: "밝은 낮 시간에 만나 서로의 안전을 지키세요.",
    safetyPoint3: "후기를 통해 신뢰할 수 있는 이웃과 연결되세요.",
    points: "크레딧",
    condition: "상태",
    location: "위치",
    exchange: "교환 신청",
    footerDisclaimer: "연(Yeon)은 연결을 돕는 플랫폼이며, 거래의 직접적인 당사자가 아닙니다.",
    legal: "이용 약관",
    statsTitle: "지역별 분포",
    login: "로그인",
    welcome: "환영합니다",
    newArrivals: "새로운 이야기",
    howItWorks: "여정",
    step1Title: "비움",
    step1Desc: "다 읽은 책을 새로운 주인에게 보냅니다.",
    step2Title: "채움",
    step2Desc: "내 주변의 새로운 지혜를 찾아보세요.",
    step3Title: "이음",
    step3Desc: "안전하게 만나 책과 마음을 나눕니다.",
    damagePolicy: "배려와 보상",
    damageDesc: "책을 소중히 다루는 법과 보상 기준."
  }
};

export const mockBooks: Book[] = [
  {
    id: '1',
    title: '트렌드 코리아 2025',
    author: '김난도',
    isbn: '9788901234567',
    condition: 'New',
    ownerId: 'u1',
    ownerName: 'Kim Min-ji',
    location: { suburb: 'Strathfield', state: 'NSW' },
    points: 15,
    imageUrl: 'https://picsum.photos/seed/book1/300/450',
    category: 'Economy'
  },
  {
    id: '2',
    title: '불편한 편의점',
    author: '김호연',
    isbn: '9788901234568',
    condition: 'Good',
    ownerId: 'u2',
    ownerName: 'Lee Jun-ho',
    location: { suburb: 'Eastwood', state: 'NSW' },
    points: 10,
    imageUrl: 'https://picsum.photos/seed/book2/300/450',
    category: 'Fiction'
  },
  {
    id: '3',
    title: '파친코 1',
    author: '이민진',
    isbn: '9788901234569',
    condition: 'Like New',
    ownerId: 'u3',
    ownerName: 'Park Su-jin',
    location: { suburb: 'Box Hill', state: 'VIC' },
    points: 12,
    imageUrl: 'https://picsum.photos/seed/book3/300/450',
    category: 'Fiction'
  },
  {
    id: '4',
    title: '채식주의자',
    author: '한강',
    isbn: '9788901234570',
    condition: 'Acceptable',
    ownerId: 'u4',
    ownerName: 'Choi Ji-hoon',
    location: { suburb: 'Sunnybank', state: 'QLD' },
    points: 8,
    imageUrl: 'https://picsum.photos/seed/book4/300/450',
    category: 'Fiction'
  },
  {
    id: '5',
    title: '소년이 온다',
    author: '한강',
    isbn: '9788901234571',
    condition: 'New',
    ownerId: 'u5',
    ownerName: 'Grace Kim',
    location: { suburb: 'Chatswood', state: 'NSW' },
    points: 15,
    imageUrl: 'https://picsum.photos/seed/book5/300/450',
    category: 'History'
  },
  {
    id: '6',
    title: '아몬드',
    author: '손원평',
    isbn: '9788901234572',
    condition: 'Good',
    ownerId: 'u6',
    ownerName: 'Daniel Park',
    location: { suburb: 'Canning Vale', state: 'WA' },
    points: 10,
    imageUrl: 'https://picsum.photos/seed/book6/300/450',
    category: 'Young Adult'
  },
  {
    id: '7',
    title: '지구 끝의 온실',
    author: '김초엽',
    isbn: '9788901234573',
    condition: 'Like New',
    ownerId: 'u7',
    ownerName: 'Sarah Lee',
    location: { suburb: 'Melbourne CBD', state: 'VIC' },
    points: 13,
    imageUrl: 'https://picsum.photos/seed/book7/300/450',
    category: 'Sci-Fi'
  },
  {
    id: '8',
    title: '달러구트 꿈 백화점',
    author: '이미예',
    isbn: '9788901234574',
    condition: 'Good',
    ownerId: 'u8',
    ownerName: 'James Cho',
    location: { suburb: 'Gold Coast', state: 'QLD' },
    points: 11,
    imageUrl: 'https://picsum.photos/seed/book8/300/450',
    category: 'Fantasy'
  }
];

export const regionData = [
  { name: 'NSW', value: 52 },
  { name: 'QLD', value: 19 },
  { name: 'VIC', value: 15 },
  { name: 'WA', value: 6 },
  { name: 'Other', value: 8 },
];