
import { Book, Chat, Translations, User, ExchangeTransaction, Discussion } from './types';

export const translations: Translations = {
  en: {
    appTitle: "Yeon.",
    heroTitle: "Embrace\nConnection",
    heroSubtitle: "Welcome to Yeon (연), where books find new paths. A mindful exchange community for Korean literature in Australia.",
    findBooks: "Discover Books",
    addBook: "Share a Story",
    searchPlaceholder: "Search for titles, authors, or meaning...",
    filterByState: "Region",
    allStates: "Everywhere",
    safetyTitle: "Mindful Exchange",
    safetyDesc: "Trust and safety are the foundation of our community.",
    safetyPoint1: "Meet in open, public spaces like libraries or cafes.",
    safetyPoint2: "Exchange during daylight to ensure clarity and safety.",
    safetyPoint3: "Connect with verified members through reviews.",
    points: "credits",
    condition: "Condition",
    location: "Origin",
    exchange: "Connect",
    footerDisclaimer: "Yeon is a platform for connection. We facilitate the meeting of minds but are not party to transactions.",
    legal: "Terms of Harmony",
    statsTitle: "Community Flow",
    login: "Sign In",
    logout: "Sign Out",
    welcome: "Welcome",
    newArrivals: "Discover Stories",
    howItWorks: "The Journey",
    step1Title: "Release",
    step1Desc: "Let go of books you've loved.",
    step2Title: "Discover",
    step2Desc: "Find new wisdom near you.",
    step3Title: "Connect",
    step3Desc: "Meet safely and share the joy.",
    damagePolicy: "Restoration Policy",
    damageDesc: "Guidelines for respect and care of shared books.",
    messages: "Messages",
    typeMessage: "Type your message...",
    send: "Send",
    contactOwner: "Message",
    requestExchange: "Request Swap",
    activeNow: "Active Now",
    noMessages: "No messages yet. Start the conversation.",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    welcomeBack: "Welcome Back",
    welcomeBackDesc: "Continue your journey of reading and connection.",
    joinUs: "Join the Flow",
    joinUsDesc: "Become part of the story today.",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already a member?",
    signUp: "Sign Up",
    signIn: "Sign In",
    myLibrary: "My Library",
    uploadBook: "Upload Book",
    uploadDesc: "Pass on the stories that moved you.",
    bookTitle: "Book Title",
    author: "Author",
    selectCondition: "Select Condition",
    selectCategory: "Select Category",
    uploadButton: "Add to Collection",
    proposalSent: "Exchange Proposal Sent",
    proposalTitle: "Exchange Proposed",
    proposalDesc: "offered in exchange for",
    accept: "Accept",
    decline: "Decline",
    accepted: "Proposal Accepted",
    rejected: "Proposal Declined",
    autoRejected: "Item Unavailable",
    selectBookToOffer: "Select a book to offer",
    selectBookDesc: "Which of your books would you like to trade for",
    selected: "Selected",
    noBooksInLibrary: "Your library is empty. Upload a book to start exchanging.",
    uploadFirst: "Upload Now",
    cancel: "Cancel",
    confirmProposal: "Send Proposal",
    yourBook: "Your Book",
    profile: "Profile",
    editProfile: "Edit Profile",
    memberSince: "Member since",
    exchangesCompleted: "Exchanges",
    communityRating: "Rating",
    exchangeHistory: "Exchange History",
    historyEmpty: "No past exchanges found.",
    tradedWith: "Traded with",
    gave: "Gave",
    received: "Received",
    completed: "Completed",
    cancelled: "Cancelled",
    pending: "Pending",
    saveChanges: "Save Changes",
    favoriteQuote: "Favorite Quote",
    quotePlaceholder: "Share a line that resonates with you...",
    discussions: "Discussions",
    activeDiscussions: "Participating Rooms",
    noDiscussions: "You haven't joined any discussions yet.",
    participants: "Participants",
    
    // Legal & Policy Text
    termsTitle: "Terms of Harmony",
    termsContent: "**1. The Platform Role**\nYeon is a neutral venue designed to facilitate the exchange of books between individuals. We do not own, sell, or inspect the books listed. Users are solely responsible for their interactions, the quality of books exchanged, and their personal safety.\n\n**2. User Conduct**\nBy using Yeon, you agree to communicate respectfully, honour your exchange commitments, and meet in safe public locations. Harassment or fraudulent behavior will result in immediate account suspension.\n\n**3. Liability**\nYeon is not liable for any loss, damage, or injury arising from exchanges. We act solely as a connector.",
    privacyTitle: "Privacy Policy",
    privacyContent: "**1. Data Collection**\nWe value your privacy and comply with the Australian Privacy Principles. We collect only the minimum information required to facilitate exchanges: your name, rough location (Suburb/State), and email for account management.\n\n**2. Location Privacy**\nYour precise address is never shared publicly. Matches are made based on suburb-level data.\n\n**3. Data Usage**\nWe do not sell your personal data to third parties. Data is used strictly for app functionality and community safety monitoring.",
    damageTitle: "Damage & Restitution",
    damageContent: "**1. Defining Damage**\nNormal wear and tear (slight yellowing, minor creasing of the spine) is acceptable in used books. However, the following constitute damage requiring compensation:\n• Water damage or mold (health hazard)\n• Missing or torn pages\n• Heavy highlighting or writing that obscures text\n• Broken spine or detached covers\n\n**2. Replacement First Policy**\nIf a book is damaged while in your care, the primary remedy is to replace it with a copy of the same ISBN or a newer edition in 'Good' or better condition.\n\n**3. Financial Compensation**\nIf a replacement cannot be sourced, the borrower is liable for the replacement cost. Following Australian university library standards, a standard fee (approx. AU $125) or the current market value (plus shipping) applies.\n\n**4. Honesty & Reporting**\nAccidents happen. If you damage a book, please inform the owner immediately via chat. Community members who self-report are often treated with more leniency regarding fees.\n\n**5. Dispute Resolution**\nAlways inspect books upon meeting. Once the exchange is complete, the condition is accepted 'as-is' unless hidden damage is discovered within 24 hours."
  },
  ko: {
    appTitle: "연 (Yeon).",
    heroTitle: "책, 그리고\n연(緣)을 잇다",
    heroSubtitle: "책이 머무는 곳에서 새로운 인연이 시작됩니다. 호주 한인들을 위한 깊이 있는 독서 교환 커뮤니티.",
    findBooks: "책 발견하기",
    addBook: "이야기 나누기",
    searchPlaceholder: "제목, 작가, 혹은 마음을 검색하세요...",
    filterByState: "지역",
    allStates: "전체",
    safetyTitle: "안전한 만남",
    safetyDesc: "신뢰는 우리 커뮤니티의 가장 중요한 가치입니다.",
    safetyPoint1: "도서관이나 카페 같은 열린 공간에서 만나세요.",
    safetyPoint2: "밝은 낮 시간에 만나 서로의 안전을 지키세요.",
    safetyPoint3: "후기를 통해 신뢰할 수 있는 이웃과 연결되세요.",
    points: "크레딧",
    condition: "상태",
    location: "위치",
    exchange: "교환 신청",
    footerDisclaimer: "연(Yeon)은 연결을 돕는 플랫폼이며, 거래의 직접적인 당사자가 아닙니다.",
    legal: "이용 약관",
    statsTitle: "지역별 분포",
    login: "로그인",
    logout: "로그아웃",
    welcome: "환영합니다",
    newArrivals: "새로운 이야기",
    howItWorks: "여정",
    step1Title: "비움",
    step1Desc: "다 읽은 책을 새로운 주인에게 보냅니다.",
    step2Title: "채움",
    step2Desc: "내 주변의 새로운 지혜를 찾아보세요.",
    step3Title: "이음",
    step3Desc: "안전하게 만나 책과 마음을 나눕니다.",
    damagePolicy: "배려와 보상",
    damageDesc: "책을 소중히 다루는 법과 보상 기준.",
    messages: "메시지",
    typeMessage: "메시지를 입력하세요...",
    send: "전송",
    contactOwner: "대화하기",
    requestExchange: "교환 요청",
    activeNow: "활동 중",
    noMessages: "메시지가 없습니다. 대화를 시작해보세요.",
    email: "이메일 주소",
    password: "비밀번호",
    name: "이름",
    welcomeBack: "다시 오셨군요",
    welcomeBackDesc: "독서와 만남의 여정을 계속하세요.",
    joinUs: "함께하기",
    joinUsDesc: "지금 새로운 이야기의 주인공이 되세요.",
    dontHaveAccount: "계정이 없으신가요?",
    alreadyHaveAccount: "이미 계정이 있으신가요?",
    signUp: "가입하기",
    signIn: "로그인",
    myLibrary: "내 서재",
    uploadBook: "책 등록하기",
    uploadDesc: "당신을 감동시킨 이야기를 나누어주세요.",
    bookTitle: "책 제목",
    author: "작가",
    selectCondition: "상태 선택",
    selectCategory: "카테고리 선택",
    uploadButton: "서재에 담기",
    proposalSent: "교환 제안이 전송되었습니다",
    proposalTitle: "교환 제안",
    proposalDesc: "을(를) 다음 책과 교환하고 싶어합니다:",
    accept: "수락",
    decline: "거절",
    accepted: "제안 수락됨",
    rejected: "제안 거절됨",
    autoRejected: "이미 교환됨",
    selectBookToOffer: "교환할 책 선택",
    selectBookDesc: "상대방의 책과 교환하기 위해 내 서재에서 책을 골라주세요:",
    selected: "선택됨",
    noBooksInLibrary: "서재가 비어있습니다. 교환을 위해 먼저 책을 등록해주세요.",
    uploadFirst: "책 등록하러 가기",
    cancel: "취소",
    confirmProposal: "제안 보내기",
    yourBook: "나의 책",
    profile: "프로필",
    editProfile: "프로필 수정",
    memberSince: "가입일",
    exchangesCompleted: "거래 완료",
    communityRating: "매너 온도",
    exchangeHistory: "교환 내역",
    historyEmpty: "지난 교환 내역이 없습니다.",
    tradedWith: "교환 파트너",
    gave: "보낸 책",
    received: "받은 책",
    completed: "완료됨",
    cancelled: "취소됨",
    pending: "대기중",
    saveChanges: "저장하기",
    favoriteQuote: "인생의 문장",
    quotePlaceholder: "마음에 울림을 준 문장을 공유해주세요...",
    discussions: "참여 중인 토론",
    activeDiscussions: "토론방",
    noDiscussions: "참여 중인 토론이 없습니다.",
    participants: "참여",

    // Legal & Policy Text (Korean)
    termsTitle: "이용 약관 (Terms of Harmony)",
    termsContent: "**1. 플랫폼의 역할**\n연(Yeon)은 개인 간의 책 교환을 돕기 위한 중립적인 플랫폼입니다. 저희는 등록된 책을 소유하거나 판매하지 않으며, 모든 교환 과정, 책의 품질 확인, 그리고 개인의 안전에 대한 책임은 사용자 본인에게 있습니다.\n\n**2. 사용자 수칙**\n서비스를 이용함으로써 귀하는 상대방을 존중하고, 약속을 성실히 이행하며, 안전한 공공장소에서 만날 것에 동의합니다. 부적절한 언행이나 사기 행위는 즉시 계정 정지 사유가 됩니다.\n\n**3. 책임의 제한**\n연(Yeon)은 교환 과정에서 발생하는 손실, 손상 또는 분쟁에 대해 법적 책임을 지지 않습니다.",
    privacyTitle: "개인정보 처리방침",
    privacyContent: "**1. 수집하는 정보**\n호주 개인정보 보호 원칙(Australian Privacy Principles)을 준수합니다. 교환 매칭을 위해 필요한 최소한의 정보(이름, 대략적인 위치, 독서 취향)만을 수집합니다.\n\n**2. 위치 정보 보호**\n귀하의 정확한 상세 주소는 공개되지 않으며, 매칭은 Suburb(동네) 단위로만 이루어집니다.\n\n**3. 정보의 사용**\n수집된 데이터는 서비스 운영과 커뮤니티 안전 모니터링 목적으로만 사용되며, 제3자에게 판매되지 않습니다.",
    damageTitle: "손상 및 보상 규정",
    damageContent: "**1. 손상 기준 정의**\n책의 자연스러운 변색이나 가벼운 구김은 '생활 기스'로 간주합니다. 그러나 다음의 경우는 손상으로 분류됩니다:\n• 물에 젖거나 곰팡이가 핀 경우 (위생 문제)\n• 페이지가 찢어지거나 분실된 경우\n• 텍스트를 가릴 정도의 낙서나 밑줄\n• 제본이 뜯어지거나 표지가 파손된 경우\n\n**2. 실물 교환 원칙**\n책이 손상된 경우, 동일한 ISBN 혹은 최신 개정판(상태 'Good' 이상)으로 구해 변상하는 것을 최우선으로 합니다.\n\n**3. 금전적 보상**\n책을 구할 수 없는 경우, 해당 도서의 현재 시세에 배송비를 더한 금액을 보상해야 합니다. 희귀 도서의 경우 호주 대학 도서관 기준에 따라 약 AU $125의 표준 보상금이 적용될 수 있습니다.\n\n**4. 자진 신고**\n실수는 누구나 할 수 있습니다. 손상이 발생하면 즉시 채팅으로 알리고 사과해주세요. 정직한 소통은 불필요한 분쟁을 막습니다.\n\n**5. 현장 확인**\n교환 시 현장에서 책 상태를 꼼꼼히 확인해주세요. 교환이 완료된 후에는 24시간 내에 숨겨진 손상이 발견되지 않는 한 '있는 그대로(as-is)' 인수한 것으로 간주합니다."
  }
};

export const currentUser: User = {
  id: 'me',
  name: 'Ji-Min Han',
  email: 'jimin.han@example.com',
  state: 'NSW',
  suburb: 'Strathfield',
  points: 125,
  booksRead: 14,
  exchangesCompleted: 8,
  rating: 4.8,
  joinDate: 'September 2024',
  avatarUrl: 'https://i.pravatar.cc/150?u=me',
  favoriteQuote: "We read to know we are not alone. – C.S. Lewis"
};

export const mockExchanges: ExchangeTransaction[] = [
  {
    id: 't1',
    bookGivenTitle: 'The Vegetarian',
    bookGivenImage: 'https://picsum.photos/seed/book4/100/150',
    bookReceivedTitle: 'Almond',
    bookReceivedImage: 'https://picsum.photos/seed/book6/100/150',
    partnerName: 'Daniel Park',
    date: 'Oct 12, 2024',
    status: 'Completed'
  },
  {
    id: 't2',
    bookGivenTitle: 'Trend Korea 2024',
    bookGivenImage: 'https://picsum.photos/seed/book99/100/150',
    bookReceivedTitle: 'Pachinko',
    bookReceivedImage: 'https://picsum.photos/seed/book3/100/150',
    partnerName: 'Park Su-jin',
    date: 'Sep 28, 2024',
    status: 'Completed'
  }
];

export const mockDiscussions: Discussion[] = [
  {
    id: 'd1',
    bookTitle: 'Pachinko',
    topic: 'Identiy across generations',
    participantsCount: 15,
    lastActive: '2 hours ago',
    imageUrl: 'https://picsum.photos/seed/book3/100/150',
  },
  {
    id: 'd2',
    bookTitle: 'Vegetarian',
    topic: 'Symbolism of refusal',
    participantsCount: 8,
    lastActive: 'Yesterday',
    imageUrl: 'https://picsum.photos/seed/book4/100/150',
  }
];

export const mockBooks: Book[] = [
  {
    id: '1',
    title: '트렌드 코리아 2025',
    author: '김난도',
    isbn: '9788901234567',
    condition: 'New',
    ownerId: 'u1',
    ownerName: 'Kim Min-ji',
    location: { suburb: 'Strathfield', state: 'NSW' },
    points: 15,
    imageUrl: 'https://picsum.photos/seed/book1/300/450',
    category: 'Economy',
    status: 'Available'
  },
  {
    id: '2',
    title: '불편한 편의점',
    author: '김호연',
    isbn: '9788901234568',
    condition: 'Good',
    ownerId: 'u2',
    ownerName: 'Lee Jun-ho',
    location: { suburb: 'Eastwood', state: 'NSW' },
    points: 10,
    imageUrl: 'https://picsum.photos/seed/book2/300/450',
    category: 'Fiction',
    status: 'Available'
  },
  {
    id: '3',
    title: '파친코 1',
    author: '이민진',
    isbn: '9788901234569',
    condition: 'Like New',
    ownerId: 'u3',
    ownerName: 'Park Su-jin',
    location: { suburb: 'Box Hill', state: 'VIC' },
    points: 12,
    imageUrl: 'https://picsum.photos/seed/book3/300/450',
    category: 'Fiction',
    status: 'Available'
  },
  {
    id: '4',
    title: '채식주의자',
    author: '한강',
    isbn: '9788901234570',
    condition: 'Acceptable',
    ownerId: 'u4',
    ownerName: 'Choi Ji-hoon',
    location: { suburb: 'Sunnybank', state: 'QLD' },
    points: 8,
    imageUrl: 'https://picsum.photos/seed/book4/300/450',
    category: 'Fiction',
    status: 'Available'
  },
  {
    id: '5',
    title: '소년이 온다',
    author: '한강',
    isbn: '9788901234571',
    condition: 'New',
    ownerId: 'u5',
    ownerName: 'Grace Kim',
    location: { suburb: 'Chatswood', state: 'NSW' },
    points: 15,
    imageUrl: 'https://picsum.photos/seed/book5/300/450',
    category: 'History',
    status: 'Available'
  },
  {
    id: '6',
    title: '아몬드',
    author: '손원평',
    isbn: '9788901234572',
    condition: 'Good',
    ownerId: 'u6',
    ownerName: 'Daniel Park',
    location: { suburb: 'Canning Vale', state: 'WA' },
    points: 10,
    imageUrl: 'https://picsum.photos/seed/book6/300/450',
    category: 'Young Adult',
    status: 'Available'
  },
  {
    id: '7',
    title: '지구 끝의 온실',
    author: '김초엽',
    isbn: '9788901234573',
    condition: 'Like New',
    ownerId: 'u7',
    ownerName: 'Sarah Lee',
    location: { suburb: 'Melbourne CBD', state: 'VIC' },
    points: 13,
    imageUrl: 'https://picsum.photos/seed/book7/300/450',
    category: 'Sci-Fi',
    status: 'Available'
  },
  {
    id: '8',
    title: '달러구트 꿈 백화점',
    author: '이미예',
    isbn: '9788901234574',
    condition: 'Good',
    ownerId: 'u8',
    ownerName: 'James Cho',
    location: { suburb: 'Gold Coast', state: 'QLD' },
    points: 11,
    imageUrl: 'https://picsum.photos/seed/book8/300/450',
    category: 'Fantasy',
    status: 'Available'
  }
];

export const regionData = [
  { name: 'NSW', value: 52 },
  { name: 'QLD', value: 19 },
  { name: 'VIC', value: 15 },
  { name: 'WA', value: 6 },
  { name: 'Other', value: 8 },
];

export const mockChats: Chat[] = [
  {
    id: 'c1',
    partnerId: 'u2',
    partnerName: 'Lee Jun-ho',
    partnerAvatar: 'https://i.pravatar.cc/150?u=u2',
    lastMessage: 'Is the book still available?',
    lastMessageTime: '10:30 AM',
    unread: 1,
    messages: [
      { id: 'm1', senderId: 'me', text: 'Hi, I saw your copy of "Inconvenient Store".', timestamp: '10:00 AM', isMe: true },
      { id: 'm2', senderId: 'u2', text: 'Hello! Yes, it is.', timestamp: '10:05 AM', isMe: false },
      { id: 'm3', senderId: 'me', text: 'Great, I live in Eastwood too.', timestamp: '10:15 AM', isMe: true },
      { id: 'm4', senderId: 'u2', text: 'Oh really? We could meet at the library.', timestamp: '10:30 AM', isMe: false },
    ]
  },
  {
    id: 'c2',
    partnerId: 'u3',
    partnerName: 'Park Su-jin',
    partnerAvatar: 'https://i.pravatar.cc/150?u=u3',
    lastMessage: 'Thanks for the exchange!',
    lastMessageTime: 'Yesterday',
    unread: 0,
    messages: [
      { id: 'm1', senderId: 'u3', text: 'I really enjoyed reading Pachinko.', timestamp: 'Yesterday', isMe: false },
      { id: 'm2', senderId: 'me', text: 'I am glad you liked it!', timestamp: 'Yesterday', isMe: true },
    ]
  },
  {
    id: 'c3',
    partnerId: 'u7',
    partnerName: 'Sarah Lee',
    partnerAvatar: 'https://i.pravatar.cc/150?u=u7',
    lastMessage: 'When are you free?',
    lastMessageTime: 'Mon',
    unread: 0,
    messages: [
       { id: 'm1', senderId: 'me', text: 'Are you free this weekend?', timestamp: 'Mon', isMe: true },
    ]
  }
];
